# Site settings
title: Radical Cadence Group
email: rc@griffinmoe.com
description: > # this means to ignore newlines until "baseurl:"
  A collective of musicians and computer scientists making things interesting.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.radicalcadence.com" # the base hostname & protocol for your site
twitter_username: RadicalCadence
github_username:  RadicalCadence

# Build settings
markdown: kramdown
